### ISSUE TITLE
Can't get attribute '_default_unk_index'

### ISSUE THREAD

**Issue by pawankmrs** [DeepLearnXMU/NSEG#2]
'bash run.sh'  failed with following error:
Traceback (most recent call last):
  File "main.py", line 203, in <module>
    DOC.vocab = torch.load(args.vocab)
  File "anaconda3/envs/NSEG/lib/python3.6/site-packages/torch/serialization.py", line 387, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "anaconda3/envs/NSEG/lib/python3.6/site-packages/torch/serialization.py", line 574, in _load
    result = unpickler.load()
AttributeError: Can't get attribute '_default_unk_index' on <module 'torchtext.vocab' from '/anaconda3/envs/NSEG/lib/python3.6/site-packages/torchtext/vocab.py'>

**Comment by pawankmrs** [comment]
torchtext  0.4.0 seems to be the problem. torchtext 0.3.1 instead of  solves it.
